//内容国际化--i18n使用方法
var content_International = {
    en: {
        message: {
            enabled: 'enabled',
            pageTitle:'equipmentTemplate',
            pageDescr:'devicesTemplate',
            templName: 'templateName',
            productModel:'productModel',
            countryCode:'countryCode',
            // 系统--隧道代理日志
            system:'system',
            tunnelProxyLog:'tunnelProxyLog',
            systemLog:'systemLog',
            enableTunnelLog:'enableTunnelLog:',
            startUsing:'startUsing',
            endUsing:'endUsing',
            listenOnAddress:'listenOnAddress',
            listenOnAdd:'listenOnAddress ',
            portNumber:'portNumber:',
            portNum:'portNumber',
            // 系统--系统日志
            enableSystemLog:'enableSystemLog:',
            serverPortNumber:'serverPortNumber:',
            serverPortNum:'serverPortNumber ',
            logLevel:'logLevel:',
            //无线--无线-2.4G(Radio0)/无线-5.8G(Radio1)
            fragmentationSize: 'fragmentation size',
            wireless:'wreless',
            wrelessTit:'wreless',
            startUsingRadio:'startUsingRadio:',
            IEEEPattern:'IEEEPattern:',
            channelInp:'channel:',
            bandwidtyValue:'bandwidty:',
            transmittedPower:'transmittedPower(dbm):',
            transmittedPo:'transmittedPower ',
            wjetAgreement:'wjetAgreement:',
            SSIDCon:'SSID Configuration',
            advancedConf:'Advanced radio settings',
            SSIDConName:'ssidConfigureName',
            SSIDName:'SSIDName',
            whetherEnable:'whetherEnable',
            whetherHide:'whetherHide',
            whetherEnablePortal:'whetherEnablePortal',
            right:'right',
            deny:'deny',
            maxTxpower:'The current largest txpower should be.',
            //table2
            total:'Article ',
            pageNum:'  the record  ',
            currentPage:' currentPage ',
            pageMidd:' page ',
            sureBtn:'sure',
            First:'First',
            Previous:'Previous',
            Next:'Next',
            Last:'Last',
            //网络
            'mtu': 'mtu',
            network:'network',
            ethPortInfo:'ethernetPortInformation',
            portNetwork:'port',
            fluidControl:'fluidControl',
            L2TPClient:'L2TPClient',
            routeConf:'routeConfiguration',
            switchConf:'switchConfiguration',
            //网络--路由配置
            rulesOfName:'rulesOfName',
            interface:'interface',
            purposeNetwork:'purposeNetwork',
            objectiveMask:'objectiveMask',
            nextHop:'nextHop',
            saveBack:'saveBack',
            cancel:'cancel',
            routingRules:'routingRules',
            newConstruction:'newConstruction',
            save:'save',
            'return':'return',
            haveError:'Errors, please checked.',
            intEditorView:'interfaceEditorView',
            interfaceIndex:'interfaceIndex',
            whetherLinked:'whetherLinked',
            alliedMouth:'alliedMouth',
            partOfMouth:'partOfMouth',
            uploadSpeed:'uploadSpeed',
            downloadSpeed:'downloadSpeed',
            egress:'egress',
            ingress:'ingress',
            flowControlRules:'flowControlRules',
            noAnyConf:'noAnyConfiguration',
            //网络--交换机配置
            newRules:' newRules',
            interfaceName:'interfaceName',
            systemPattern:'systemPattern',
            portNumb:'portNum',
            redact:' redact',
            'delete':' delete',
            handle:'handle',
            OVS_switch:'OVS Switch',
            'vni': 'vni',
            'vlan_id': 'vlan id',
            SysBridge:'SystemBridge',
            switchTnterfaceName:'switchTnterfaceName:',
            switchModel:'switchModel:',
            thePortName:'thePortName:',
            thePortNames:'thePortName ',
            thePortNumber:'thePortNumber:',
            vlanType:'vlanType:',
            vlanTypes:'vlanType ',
            thePortType:'thePortType:',
            portTypes:'thePortType ',
            toIPAddress:'toIPAddress:',
            IPAddress:'IPAddress ',
            whetherWifiInt:'whetherWifiInterface:',
            radioIndex:'radioIndex：',
            ssidName:'ssidName',
            exchangeRules:'exchangeRules',
            addSave:'addSave',
            editSave:'editSave',
            vlanId:'vlanId',
            whetherWifi:'whetherWifi',
            radioNumber:'radioNumber',
            thePortNum:'thePortNum',
            modifyAgain:'Port name is not the only, please modify it again.',
            ovsBridgeModel:'ovsBridgeModel',
            notSupportMode:'Does not support the mode.',
            noParentValue:'There is no parent value.',
            intNameNotOnly:'The interface name is not the only, please modify it again.',
            ruleNameNotOnly:'the rule name is exists, please modify it',
            //网络 --接口
            agentargs: 'agentargs',
            interfaceRule: 'interface rule',
            iftype: 'interface type',
            ifname: 'interface name',
            idletimeout: 'idle timeout',
            accttimeout: 'acct timeout',
            nasAddr: 'NAS ipaddr',
            prtIpaddr: 'Portal ipaddr',
            prtUrl: 'Portal url',
            commonAdd: 'Add',
            commonDel: 'Delete',
            commonFlush: 'Delete all items',
            commonIndex: 'index',
            commonEqual: 'equal',
            commonExists: 'already exists',
            dstDenyIp4: 'Dest block IPv4 address',
            dstDenyHost: 'Dest block host address',
            dstFreeIp4: 'Dest access IPv4 address',
            dstFreeHost: 'Dest access host address',
            portalSetting: 'Portal settings',
            macAuth:'MAC without perception settings',
            radAuthAccount:'Radius auth and account settings',
            radAuthServer: 'Radius auth server',
            radAccountServer: 'Radius account server',
            macAuthSession:'Pre release time',
            srcPolicy: 'Source address policy settings',
            srcIPBlock: 'Source IP block list',
            srcMACBlock: 'Source MAC block list',
            srcIPAccept: 'Source IP accept list',
            srcMACAccept: 'Source MAC accept list',
            portalRedirectMethod: 'Portal redirect method',
            //外部事件-内部事件
            externalEvent:'externalEvent',
            internalEvent:'internalEvent',
            //无数据
            nullMsg:'null_msg',
            //保存完成
            saveFinish:'saveFinish'
        }
    },
    zh_CN: {
        message: {
            enabled: '启用',
            pageTitle:'设备模版',
            pageDescr:'配置一个设备模版',
            templName: '模版名称',
            productModel:'产品型号',
            countryCode:'国家代码',
            // 系统--隧道代理日志
            system:'系统',
            tunnelProxyLog:'隧道代理日志',
            systemLog:'系统日志',
            enableTunnelLog:'启用隧道日志 :',
            startUsing:'启用',
            endUsing:'禁用',
            listenOnAddress:'监听地址 :',
            listenOnAdd:'监听地址 ',
            portNumber:'端口号 :',
            portNumb:'端口号 ',
            // 系统--系统日志
            enableSystemLog:'启用系统日志 :',
            serverPortNumber:'服务器端口号 :',
            serverPortNum:'服务器端口号 ',
            logLevel:'日志等级 :',
            //无线--无线-2.4G(Radio0)/无线-5.8G(Radio1)
            fragmentationSize: 'fragmentation size',
            wireless:'无线',
            wrelessTit:'无线',
            startUsingRadio:'启用Radio：',
            IEEEPattern:'IEEE模式：',
            channelInp:'信道：',
            bandwidtyValue:'频宽：',
            transmittedPower:'发射功率(dbm)：',
            transmittedPo:'发射功率 ',
            wjetAgreement:'wjet协议：',
            SSIDCon:'SSID配置 ',
            advancedConf:'Radio 高级设置',
            SSIDConName:'SSID配置名称',
            SSIDName:'SSID名称',
            whetherEnable:'是否启用',
            whetherHide:'是否隐藏',
            whetherEnablePortal:'是否开启Portal',
            right:'是',
            deny:'否',
            maxTxpower:'当前最大txpower应该为',
            //table2
            total:'共 ',
            pageNum:'页',
            currentPage:'  当前页  ',
            jumpPage:'跳至',
            pageMidd:'页',
            sureBtn:'确定',
            First:'首页',
            Previous:'上一页',
            Next:'下一页',
            Last:'尾页',
            //网络
            'mtu': 'mtu',
            network:'网络',
            ethPortInfo:'以太口信息',
            portNetwork:'接口',
            fluidControl:'流控',
            L2TPClient:'L2TP客户端',
            routeConf:'路由配置',
            switchConf:'交换机配置',
            //网络--路由配置
            rulesOfName:'规则名',
            interface:'接口',
            purposeNetwork:'目的网络',
            objectiveMask:'目的掩码',
            nextHop:'下一跳',
            saveBack:'保存并返回',
            cancel:'取消',
            routingRules:'路由规则',
            newConstruction:'新建',
            save:'保存',
            'return':'返回',
            haveError:'存在错误，请检查',
            intEditorView:'接口编辑视图',
            interfaceIndex:'接口索引',
            whetherLinked:'是否为上联口',
            alliedMouth:'上联口',
            partOfMouth:'非上联口',
            uploadSpeed:'上传速率',
            downloadSpeed:'下载速率',
            egress:'上行速率',
            ingress:'下行速率',
            flowControlRules:'流控规则',
            noAnyConf:'尚无任何配置',
            //网络--交换机配置
            newRules:' 新建规则',
            interfaceName:'接口名',
            systemPattern:'系统模式',
            portNum:'端口数量',
            redact:' 编辑',
            'delete':' 删除',
            handle:'操作',
            OVS_switch:'OVS交换',
            'vni': 'vni',
            'vlan_id': 'vlan id',
            SysBridge:'系统桥接',
            switchTnterfaceName:'交换机接口名：',
            switchModel:'switch模式：',
            thePortName:'端口名：',
            thePortNames:'端口名 ',
            thePortNumber:'端口号：',
            vlanType:'vlan类型：',
            vlanTypes:'vlan类型 ',
            thePortType:'端口类型：',
            portTypes:'端口类型 ',
            toIPAddress:'对端IP地址：',
            IPAddress:'对端IP地址 ',
            whetherWifiInt:'是否是wifi接口：',
            radioIndex:'radio索引号：',
            ssidName:'ssid名称',
            exchangeRules:'交换机规则',
            addSave:'添加并保存',
            editSave:'编辑并保存',
            vlanId:'vlan号',
            whetherWifi:'是否为wifi',
            radioNumber:'radio编号',
            thePortNum:'端口编号',
            modifyAgain:'端口名不唯一,请重新修改',
            ovsBridgeModel:'ovs桥接模式',
            notSupportMode:'不支持的模式',
            noParentValue:'不存在的父级值',
            intNameNotOnly:'接口名不唯一,请重新修改',
            ruleNameNotOnly:'规则名已存在，请修改',
            //网络 --接口
            agentargs: 'agent参数',
            interfaceRule: '接口规则',
            iftype: '接口类型',
            ifname: '接口名称',
            idletimeout: 'idle超时时长',
            accttimeout: 'account超时时长',
            nasAddr: 'NAS 地址',
            prtIpaddr: 'Portal 重定向IP地址',
            prtUrl: 'Portal 重定向URL',
            commonAdd: '添加',
            commonDel: '删除',
            commonFlush: '删除所有条目',
            commonIndex: '索引',
            commonEqual: '相等',
            commonExists: '已存在',
            dstDenyIp4: '目的地址 IPv4黑名单',
            dstDenyHost: '目的地址 域名黑名单',
            dstFreeIp4: '目的地址 IPV4白名单',
            dstFreeHost: '目的地址 HOST白名单',
            portalSetting: 'Portal设置',
            macAuth:'MAC无感知设置',
            radAuthAccount:'Radius认证及计费设置',
            radAuthServer: 'Radius认证服务器',
            radAccountServer: 'Radius记账服务器',
            macAuthSession:'预放行时长',
            srcPolicy: '源地址策略设置',
            srcIPBlock: '源IP黑名单',
            srcMACBlock: '源MAC黑名单',
            srcIPAccept: '源IP白名单',
            srcMACAccept: '源MAC白名单',
            portalRedirectMethod: 'Portal重定向方法',
            //外部事件-内部事件
            externalEvent:'外部事件',
            internalEvent:'内部事件',
            //无数据
            nullMsg:'无数据',
            //保存完成
            saveFinish:'保存完成'
        }
    }
}


//设置locals语言包
Object.keys(content_International).forEach(function (lang) {
    Vue.locale(lang, content_International[lang])
})
//设置当前语言

//你也可以这么用，编程式,Vue.t("message.templName")
//Vue.locale('cn', locales['cn'])
//在组件内，请添加locales属性，它与template同级
//					locales: {
//	              en: { hello: 'hello component1' },
//	              ja: { hello: 'こんにちは、component1' }
//	            }

function vue_set_language(lang){
      //lang is 'zh_CN' or 'en'
      Vue.config.lang = lang;
}
